const Images={
    logo:new URL('./Shaddan-Textile-Logo.png',import.meta.url).href,
    banner:new URL("./shaddan-banner.jpg",import.meta.url).href,
banner2:new URL("./shaddan-banner2.png",import.meta.url).href,
towels:new URL("./Towel.webp",import.meta.url).href,
garments:new URL("./Garments.webp",import.meta.url).href,    
sheets:new URL("./sheets.webp",import.meta.url).href,
Bathrobes:new URL("./Bathrobes.webp",import.meta.url).href,
icon1:new URL("./icon1.png",import.meta.url).href,
icon2:new URL("./icon2.png",import.meta.url).href,
icon3:new URL("./icon3.png",import.meta.url).href,
icon4:new URL("./icon4.png",import.meta.url).href,
Quality:new URL("./Quality.webp",import.meta.url).href,
Dyeing:new URL("./Dyeing finishing.webp",import.meta.url).href,
Fabric:new URL("./fabric.webp",import.meta.url).href,
Garments:new URL("./Garments devisions.webp",import.meta.url).href,
Factoryimage1:new URL("./F1.webp",import.meta.url).href,
Factoryimage2:new URL("./F2.webp",import.meta.url).href,
Factoryimage3:new URL("./F3.webp",import.meta.url).href,    
Factoryimage4:new URL("./F4.webp",import.meta.url).href,
Factoryimage5:new URL("./F5.webp",import.meta.url).href,
Factoryimage6:new URL("./F6.webp",import.meta.url).href,
Factoryimage7:new URL("./F7.webp",import.meta.url).href,            
Factoryimage8:new URL("./F8.webp",import.meta.url).href,
Factoryimage9:new URL("./F9.webp",import.meta.url).href,
Factoryimage10:new URL("./F10.webp",import.meta.url).href,
Factoryimage11:new URL("./F11.webp",import.meta.url).href,
Factoryimage12:new URL("./F12.webp",import.meta.url).href,
Factoryimage13:new URL("./F13.webp",import.meta.url).href,
Factoryimage14:new URL("./F14.webp",import.meta.url).href,
Factoryimage15:new URL("./F15.webp",import.meta.url).href,  
Factoryimage16:new URL("./F16.webp",import.meta.url).href,
Factoryimage17:new URL("./F18.webp",import.meta.url).href,
Factoryimage18:new URL("./F19.webp",import.meta.url).href,
Factoryimage19:new URL("./F20.webp",import.meta.url).href,

}
export default Images;
